### ISSUE TITLE
Crash when subscribe to layoutChanged event 

### ISSUE THREAD

**Issue by ammarahm-ed** [triniwiz/nativescript-mason#14]
Subscribing to layoutChanged event causes a crash. Happens on both flex/grid & any child view such as a label/button
```
An uncaught Exception occurred on "main" thread.
Calling js method onLayoutChange failed
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TypeSelector'
    |     property 'ruleset' -> object with constructor 'RuleSet'
    |     property 'selectors' -> object with constructor 'Array'
    --- index 0 closes the circle
File: (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.52a652261f245a6704f6.hot-update.js:42:14)

StackTrace: 
(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.52a652261f245a6704f6.hot-update.js:42:15)
	at runEventHandlers(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:76492:12)
	at dispatchEvent(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:76751:7)
	at nativeHandler(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:59033:10)
	at _handleEvent(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:5527:41)
	at notify(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:5508:24)
	at _raiseLayoutChangedEvent(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:20334:14)
	at onLayoutChange(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:19143:39)


TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TypeSelector'
    |     property 'ruleset' -> object with constructor 'RuleSet'
    |     property 'selectors' -> object with constructor 'Array'
    --- index 0 closes the circle

StackTrace:
(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.52a652261f245a6704f6.hot-update.js:42:15)
	at runEventHandlers(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:76492:12)
	at dispatchEvent(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:76751:7)
	at nativeHandler(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:59033:10)
	at _handleEvent(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:5527:41)
	at notify(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:5508:24)
	at _raiseLayoutChangedEvent(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:20334:14)
	at onLayoutChange(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:19143:39)
	at runEventHandlers(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:76492:12)
	at dispatchEvent(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:76751:7)
	at nativeHandler(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:59033:10)
	at _handleEvent(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:5527:41)
	at notify(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:5508:24)
	at _raiseLayoutChangedEvent(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:20334:14)
	at onLayoutChange(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:19143:39)


TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TypeSelector'
    |     property 'ruleset' -> object with constructor 'RuleSet'
    |     property 'selectors' -> object with constructor 'Array'
    --- index 0 closes the circle
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
	at com.tns.gen.android.view.View_OnLayoutChangeListener.onLayoutChange(View_OnLayoutChangeListener.java:35)
	at android.view.View.layout(View.java:23161)
	at org.nativescript.mason.masonkit.View.applyLayoutRecursive(View.kt:166)
	at org.nativescript.mason.masonkit.View.applyLayoutRecursive(View.kt:174)
	at org.nativescript.mason.masonkit.View.onLayout(View.kt:197)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:351)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:351)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:798)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3684)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3143)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

**Comment by triniwiz** [comment]
Works on vanilla 👀

**Comment by ammarahm-ed** [comment]
I'll look into it, maybe vanilla is on mason drugs :P lol
